// (c) Roel Kluin 2024 GPL v3
//! Build script for ranting: generates irregular verb table (past forms only)
//! for the detect_tense function, from the shared data/irregular_verbs.txt file.

use std::env;
use std::fs;
use std::io::{self, BufRead};
use std::path::PathBuf;

fn main() -> io::Result<()> {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let data_file = PathBuf::from(&manifest_dir).join("data/irregular_verbs.txt");

    println!("cargo:rerun-if-changed={}", data_file.display());

    // Read and parse the data file
    let file = fs::File::open(&data_file)?;
    let reader = io::BufReader::new(file);

    let mut irregular_past: Vec<(String, String)> = Vec::new();

    for line_result in reader.lines() {
        let line = line_result?;
        let line = line.trim();
        if line.is_empty() {
            continue;
        }

        let parts: Vec<&str> = line.split('|').collect();
        if parts.len() != 3 {
            panic!(
                "Invalid line format (expected base|past|participle): {}",
                line
            );
        }

        let base = parts[0].to_string();
        let past = parts[1].to_string();

        irregular_past.push((base, past));
    }

    // Generate Rust code for the IRREGULAR_PAST table only (runtime crate doesn't use participles)
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let output_path = PathBuf::from(&out_dir).join("irregular_verbs_generated.rs");

    let mut code = String::from(
        "// Generated code: irregular verb past-form table\n\
         // This file is generated by build.rs from data/irregular_verbs.txt\n\
         // Only the past forms are included (participles used only by ranting_derive)\n\n",
    );

    code.push_str("static IRREGULAR_PAST: &[(&str, &str)] = &[\n");
    for (base, past) in &irregular_past {
        code.push_str(&format!("    (\"{}\", \"{}\"),\n", base, past));
    }
    code.push_str("];\n");

    fs::write(&output_path, code)?;
    println!("Generated: {}", output_path.display());

    Ok(())
}
