// (c) Roel Kluin 2024 GPL v3
//! Build script for ranting: generates irregular verb table (past forms only)
//! for the detect_tense function, from the shared data/irregular_verbs.txt file.

use std::env;
use std::fs;
use std::io::{self, BufRead};
use std::path::PathBuf;

fn main() -> io::Result<()> {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");

    // Generate irregular verbs table
    generate_verbs_table(&manifest_dir)?;

    // Generate irregular plurals table
    generate_plurals_table(&manifest_dir)?;

    Ok(())
}

fn generate_verbs_table(manifest_dir: &str) -> io::Result<()> {
    let data_file = PathBuf::from(manifest_dir).join("data/irregular_verbs.txt");
    println!("cargo:rerun-if-changed={}", data_file.display());

    // Read and parse the data file
    let file = fs::File::open(&data_file)?;
    let reader = io::BufReader::new(file);

    let mut irregular_past: Vec<(String, String)> = Vec::new();
    let mut irregular_past_participle: Vec<(String, String)> = Vec::new();

    for line_result in reader.lines() {
        let line = line_result?;
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        let parts: Vec<&str> = line.split('|').collect();
        if parts.len() != 3 {
            panic!(
                "Invalid line format (expected base|past|participle): {}",
                line
            );
        }

        let base = parts[0].to_string();
        let past = parts[1].to_string();
        let participle = parts[2].to_string();

        irregular_past.push((base.clone(), past));
        irregular_past_participle.push((base, participle));
    }

    // Generate Rust code for both tables (participles needed by runtime verb
    // conjugation, see src/language/verb_conjugate.rs).
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let output_path = PathBuf::from(&out_dir).join("irregular_verbs_generated.rs");

    let mut code = String::from(
        "// Generated code: irregular verb conjugation tables\n\
         // This file is generated by build.rs from data/irregular_verbs.txt\n\n",
    );

    code.push_str("static IRREGULAR_PAST: &[(&str, &str)] = &[\n");
    for (base, past) in &irregular_past {
        code.push_str(&format!("    (\"{}\", \"{}\"),\n", base, past));
    }
    code.push_str("];\n\n");

    code.push_str("static IRREGULAR_PAST_PARTICIPLE: &[(&str, &str)] = &[\n");
    for (base, participle) in &irregular_past_participle {
        code.push_str(&format!("    (\"{}\", \"{}\"),\n", base, participle));
    }
    code.push_str("];\n");

    fs::write(&output_path, code)?;
    println!("Generated: {}", output_path.display());

    Ok(())
}

fn generate_plurals_table(manifest_dir: &str) -> io::Result<()> {
    let data_file = PathBuf::from(manifest_dir).join("data/irregular_plurals.txt");

    // Skip if file doesn't exist yet
    if !data_file.exists() {
        return Ok(());
    }

    println!("cargo:rerun-if-changed={}", data_file.display());

    // Read and parse the data file
    let file = fs::File::open(&data_file)?;
    let reader = io::BufReader::new(file);

    let mut irregular_plurals: Vec<(String, String)> = Vec::new();

    for line_result in reader.lines() {
        let line = line_result?;
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        let parts: Vec<&str> = line.split('|').collect();
        if parts.len() != 2 {
            panic!("Invalid line format (expected singular|plural): {}", line);
        }

        let singular = parts[0].to_string();
        let plural = parts[1].to_string();

        irregular_plurals.push((singular, plural));
    }

    // Generate Rust code for both IRREGULAR_PLURALS and IRREGULAR_SINGULARS tables
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let output_path = PathBuf::from(&out_dir).join("irregular_plurals_generated.rs");

    let mut code = String::from(
        "// Generated code: irregular noun plurals table\n\
         // This file is generated by build.rs from data/irregular_plurals.txt\n\n",
    );

    code.push_str("pub(super) static IRREGULAR_PLURALS: &[(&str, &str)] = &[\n");
    for (singular, plural) in &irregular_plurals {
        code.push_str(&format!("    (\"{}\", \"{}\"),\n", singular, plural));
    }
    code.push_str("];\n\n");

    code.push_str("pub(super) static IRREGULAR_SINGULARS: &[(&str, &str)] = &[\n");
    for (singular, plural) in &irregular_plurals {
        code.push_str(&format!("    (\"{}\", \"{}\"),\n", plural, singular));
    }
    code.push_str("];\n");

    fs::write(&output_path, code)?;
    println!("Generated: {}", output_path.display());

    Ok(())
}
