// (c) Roel Kluin 2024 MIT
//! Build script for ranting: generates the irregular noun plurals table
//! from the shared data/irregular_plurals.txt file.
//!
//! The irregular *verb* table used to be generated here too (for
//! `detect_tense`), but that codegen now lives solely in `ranting_core`'s
//! build.rs — `ranting` reads `ranting_core::verb_conjugate::IRREGULAR_PAST`
//! instead of generating its own copy (see CLAUDE.md's Architecture section).

use std::env;
use std::fs;
use std::io::{self, BufRead};
use std::path::PathBuf;

fn main() -> io::Result<()> {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");

    // Generate irregular plurals table
    generate_plurals_table(&manifest_dir)?;

    Ok(())
}

fn generate_plurals_table(manifest_dir: &str) -> io::Result<()> {
    let data_file = PathBuf::from(manifest_dir).join("data/irregular_plurals.txt");

    // Skip if file doesn't exist yet
    if !data_file.exists() {
        return Ok(());
    }

    println!("cargo:rerun-if-changed={}", data_file.display());

    // Read and parse the data file
    let file = fs::File::open(&data_file)?;
    let reader = io::BufReader::new(file);

    let mut irregular_plurals: Vec<(String, String)> = Vec::new();

    for line_result in reader.lines() {
        let line = line_result?;
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        let parts: Vec<&str> = line.split('|').collect();
        if parts.len() != 2 {
            panic!("Invalid line format (expected singular|plural): {}", line);
        }

        let singular = parts[0].to_string();
        let plural = parts[1].to_string();

        irregular_plurals.push((singular, plural));
    }

    // Generate Rust code for the IRREGULAR_PLURALS table. get_plural/get_singular
    // (src/language/plurals.rs) both scan this single table — forward for plurals,
    // reverse for singulars — so there's no separate reversed table to keep in sync.
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let output_path = PathBuf::from(&out_dir).join("irregular_plurals_generated.rs");

    let mut code = String::from(
        "// Generated code: irregular noun plurals table\n\
         // This file is generated by build.rs from data/irregular_plurals.txt\n\n",
    );

    code.push_str("pub(super) static IRREGULAR_PLURALS: &[(&str, &str)] = &[\n");
    for (singular, plural) in &irregular_plurals {
        code.push_str(&format!("    (\"{}\", \"{}\"),\n", singular, plural));
    }
    code.push_str("];\n");

    fs::write(&output_path, code)?;
    println!("Generated: {}", output_path.display());

    Ok(())
}
