[package]
name = "ranting"
version = "0.1.0"
authors = ["Roel Kluin <Roel.Kluin@gmail.com>"]
edition = "2021"

[dependencies]
ranting_derive = { version = "=0.1.0", path = "ranting_derive" }
in_definite = "0.2"
Inflector = "0.11.4"

