// (c) Roel Kluin 2026 MIT
//! Build script for ranting_core: generates the irregular verb conjugation
//! tables (`IRREGULAR_PAST`, `IRREGULAR_PAST_PARTICIPLE`) from the shared
//! `data/irregular_verbs.txt` file. This is now the *only* place these
//! tables are generated — `ranting` and `ranting_derive` both consume the
//! resulting `ranting_core::verb_conjugate` items instead of each generating
//! their own copy (see CLAUDE.md, "Architecture: Three Crates" section).

use std::env;
use std::fs;
use std::io::{self, BufRead};
use std::path::PathBuf;

fn main() -> io::Result<()> {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    generate_verbs_table(&manifest_dir)?;
    Ok(())
}

/// Locate `data/irregular_verbs.txt`:
/// 1. Dev checkout: `../data/irregular_verbs.txt`, relative to this crate's
///    manifest dir — the repo-root single source of truth.
/// 2. Packaged crate: `./data/irregular_verbs.txt`, a symlink (dev) that
///    `cargo package` dereferences to real content in the published tarball.
fn find_data_file(manifest_dir: &str) -> PathBuf {
    let dev_path = PathBuf::from(manifest_dir)
        .parent()
        .expect("parent dir")
        .join("data/irregular_verbs.txt");

    let pkg_path = PathBuf::from(manifest_dir).join("data/irregular_verbs.txt");

    if dev_path.exists() {
        dev_path
    } else if pkg_path.exists() {
        pkg_path
    } else {
        panic!(
            "Could not find data/irregular_verbs.txt at {} or {}",
            dev_path.display(),
            pkg_path.display()
        );
    }
}

fn generate_verbs_table(manifest_dir: &str) -> io::Result<()> {
    let data_file = find_data_file(manifest_dir);
    println!("cargo:rerun-if-changed={}", data_file.display());

    let file = fs::File::open(&data_file)?;
    let reader = io::BufReader::new(file);

    let mut irregular_past: Vec<(String, String)> = Vec::new();
    let mut irregular_past_participle: Vec<(String, String)> = Vec::new();
    let mut prev_base = String::new();

    for line_result in reader.lines() {
        let line = line_result?;
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        let parts: Vec<&str> = line.split('|').collect();
        if parts.len() != 3 {
            panic!(
                "Invalid line format (expected base|past|participle): {}",
                line
            );
        }

        let base = parts[0].to_string();
        let past = parts[1].to_string();
        let participle = parts[2].to_string();

        // Sanity check: no duplicate base verbs
        if base == prev_base {
            panic!("Duplicate base verb in data file: {}", base);
        }
        prev_base = base.clone();

        irregular_past.push((base.clone(), past));
        irregular_past_participle.push((base, participle));
    }

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let output_path = PathBuf::from(&out_dir).join("irregular_verbs_generated.rs");

    let mut code = String::from(
        "// Generated code: irregular verb conjugation tables\n\
         // This file is generated by build.rs from data/irregular_verbs.txt\n\n",
    );

    code.push_str("pub static IRREGULAR_PAST: &[(&str, &str)] = &[\n");
    for (base, past) in &irregular_past {
        code.push_str(&format!("    (\"{}\", \"{}\"),\n", base, past));
    }
    code.push_str("];\n\n");

    code.push_str("pub static IRREGULAR_PAST_PARTICIPLE: &[(&str, &str)] = &[\n");
    for (base, participle) in &irregular_past_participle {
        code.push_str(&format!("    (\"{}\", \"{}\"),\n", base, participle));
    }
    code.push_str("];\n");

    fs::write(&output_path, code)?;
    println!("Generated: {}", output_path.display());

    Ok(())
}
