//! Writing findings into `failures/`.
//!
//! Layout, and why:
//!
//! ```text
//! failures/
//!   README.md                  index, causes ranked by corpus occurrences
//!   summary.json               the same data, for anything that wants to consume it
//!   <cause-id>/README.md       one directory per cause
//! ```
//!
//! One directory per **cause**, not per word. `ranting` has no regular pluralization rules, which
//! breaks every noun outside a 63-line table -- writing a file per broken noun would produce
//! thousands of files that all say the same thing and bury the one fact worth acting on. The
//! frequency-ranked word table lives inside the cause's own README, where its ordering is the
//! answer to "how common is this".

use crate::finding::{Confidence, Finding, Kind};
use std::fmt::Write as _;
use std::io;
use std::path::Path;

/// Everything a run needs to describe itself in the output.
pub struct RunInfo<'a> {
    pub sources: &'a [std::path::PathBuf],
    pub files: usize,
    pub total_words: usize,
    pub min_occurrences: usize,
}

pub fn write(dir: &Path, findings: &[Finding], run: &RunInfo<'_>) -> io::Result<()> {
    // Remove only the directories this tool owns, so a stale cause from a previous run against a
    // different corpus doesn't linger and get mistaken for a current finding.
    if dir.exists() {
        for entry in std::fs::read_dir(dir)?.filter_map(Result::ok) {
            let path = entry.path();
            if path.is_dir() && path.join("README.md").exists() {
                std::fs::remove_dir_all(&path)?;
            }
        }
    }
    std::fs::create_dir_all(dir)?;

    for finding in findings {
        let sub = dir.join(finding.id);
        std::fs::create_dir_all(&sub)?;
        std::fs::write(sub.join("README.md"), cause_page(finding))?;
    }
    std::fs::write(dir.join("README.md"), index_page(findings, run))?;
    std::fs::write(
        dir.join("summary.json"),
        serde_json::to_string_pretty(&findings)? + "\n",
    )?;
    Ok(())
}

fn kind_label(kind: Kind) -> &'static str {
    match kind {
        Kind::Gap => "gap — actionable",
        Kind::Boundary => "boundary — measured, not actionable",
    }
}

fn confidence_label(c: Confidence) -> &'static str {
    match c {
        Confidence::Certain => "certain",
        Confidence::Attested => "attested",
        Confidence::Heuristic => "heuristic",
    }
}

fn index_page(findings: &[Finding], run: &RunInfo<'_>) -> String {
    let mut out = String::new();
    out.push_str("# ranting: what the corpus says it cannot do\n\n");
    out.push_str(
        "Generated by `ranting_gaps` — do not edit by hand; rerun the tool instead. Each \
         directory is one **cause**, not one word: a single missing rule can break thousands of \
         words, and the frequency-ranked table inside each cause is the answer to \"how common is \
         this\".\n\n",
    );

    let _ = writeln!(out, "## Run\n");
    let _ = writeln!(
        out,
        "| Sources | Files read | Words | Min. occurrences |\n|---|---|---|---|"
    );
    let sources = run
        .sources
        .iter()
        .map(|p| format!("`{}`", p.display()))
        .collect::<Vec<_>>()
        .join(", ");
    let _ = writeln!(
        out,
        "| {sources} | {} | {} | {} |\n",
        run.files, run.total_words, run.min_occurrences
    );

    let _ = writeln!(out, "## Causes, most frequent first\n");
    let _ = writeln!(
        out,
        "| Cause | Kind | Distinct words | Corpus occurrences |\n|---|---|---|---|"
    );
    for f in findings {
        let _ = writeln!(
            out,
            "| [{}]({}/README.md) | {} | {} | {} |",
            f.title,
            f.id,
            kind_label(f.kind),
            f.cases.len(),
            f.occurrences()
        );
    }

    let actionable: usize = findings
        .iter()
        .filter(|f| f.kind == Kind::Gap)
        .map(Finding::occurrences)
        .sum();
    let measured: usize = findings
        .iter()
        .filter(|f| f.kind == Kind::Boundary)
        .map(Finding::occurrences)
        .sum();
    let _ = write!(
        out,
        "\n{actionable} occurrences come from gaps that could be fixed; {measured} come from \
         boundaries that are decided and will not be. The split matters: a boundary count is \
         evidence about scope, not a bug report.\n\n\
         ## Reading a case table\n\n\
         - **certain** — the tool ran `ranting`'s own inflection and compared it against a rule \
         that is a function of spelling alone. No judgement about the corpus involved.\n\
         - **attested** — as *certain*, and the corpus independently writes the corrected form. \
         The strongest evidence available without a lexicon.\n\
         - **heuristic** — rests on the determiner cue in `corpus.rs` being right about this \
         word's part of speech. Read the quoted sentences before acting.\n\n\
         There is no part-of-speech tagger here. A word counts as a noun when a determiner or a \
         numeral preceded it — conservative, so the counts under-report rather than invent.\n",
    );
    out
}

fn cause_page(f: &Finding) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "# {}\n", f.title);
    let _ = writeln!(out, "**Kind:** {}  ", kind_label(f.kind));
    let _ = writeln!(out, "**Distinct words:** {}  ", f.cases.len());
    let _ = writeln!(out, "**Corpus occurrences:** {}\n", f.occurrences());

    let _ = writeln!(out, "## Cause\n\n{}\n", f.cause);
    let _ = writeln!(out, "## Why it fails\n\n{}\n", f.why_it_fails);
    let heading = match f.kind {
        Kind::Gap => "What ranting needs",
        Kind::Boundary => "Why there is nothing to do",
    };
    let _ = writeln!(out, "## {heading}\n\n{}\n", f.what_ranting_needs);

    let _ = writeln!(out, "## Cases, most frequent first\n");
    let _ = writeln!(
        out,
        "| Word | ranting renders | English requires | Occurrences | Confidence |\n\
         |---|---|---|---|---|"
    );
    for c in &f.cases {
        let _ = writeln!(
            out,
            "| `{}` | `{}` | `{}` | {} | {} |",
            c.subject,
            c.ranting_renders,
            c.expected,
            c.occurrences,
            confidence_label(c.confidence)
        );
    }

    let _ = writeln!(out, "\n## Evidence\n");
    for c in &f.cases {
        if c.examples.is_empty() {
            continue;
        }
        let _ = writeln!(out, "### `{}`\n", c.subject);
        for e in &c.examples {
            let _ = writeln!(out, "- {e}");
        }
        out.push('\n');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::finding::Case;

    fn sample(kind: Kind) -> Finding {
        Finding {
            id: "sample",
            title: "Sample",
            kind,
            cause: "c",
            why_it_fails: "w",
            what_ranting_needs: "n",
            cases: vec![Case {
                subject: "fly".into(),
                ranting_renders: "flys".into(),
                expected: "flies".into(),
                confidence: Confidence::Attested,
                occurrences: 7,
                examples: vec!["a.md:1 — The fly landed.".into()],
            }],
        }
    }

    #[test]
    fn a_cause_page_carries_all_four_questions_and_the_evidence() {
        let page = cause_page(&sample(Kind::Gap));
        for expected in [
            "## Cause",
            "## Why it fails",
            "## What ranting needs",
            "| `fly` | `flys` | `flies` | 7 | attested |",
            "a.md:1 — The fly landed.",
        ] {
            assert!(page.contains(expected), "missing {expected:?} in:\n{page}");
        }
    }

    /// A boundary must never be headed "what ranting needs" — that phrasing would turn a decision
    /// already taken into an open work item every time someone skimmed the file.
    #[test]
    fn a_boundary_page_does_not_ask_for_work() {
        let page = cause_page(&sample(Kind::Boundary));
        assert!(page.contains("## Why there is nothing to do"));
        assert!(!page.contains("## What ranting needs"));
        assert!(page.contains("boundary — measured, not actionable"));
    }

    #[test]
    fn the_index_separates_actionable_from_measured() {
        let run = RunInfo {
            sources: &[],
            files: 1,
            total_words: 10,
            min_occurrences: 2,
        };
        let page = index_page(&[sample(Kind::Gap), sample(Kind::Boundary)], &run);
        assert!(page.contains("7 occurrences come from gaps"));
        assert!(page.contains("7 come from boundaries"));
    }
}
