// (c) Roel Kluin 2024 GPL v3
//! Build script for ranting_derive: generates irregular verb conjugation tables
//! from the shared data/irregular_verbs.txt file.

use std::env;
use std::fs;
use std::io::{self, BufRead};
use std::path::PathBuf;

fn main() -> io::Result<()> {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");

    // Try to find the data file:
    // 1. First try in the symlinked location (development): ../../data/irregular_verbs.txt
    // 2. Then try in the same package dir (cargo package verification): ./data/irregular_verbs.txt
    let data_file_dev = PathBuf::from(&manifest_dir)
        .parent()
        .expect("parent dir")
        .join("data/irregular_verbs.txt");

    let data_file_pkg = PathBuf::from(&manifest_dir)
        .join("data/irregular_verbs.txt");

    let data_file = if data_file_dev.exists() {
        data_file_dev
    } else if data_file_pkg.exists() {
        data_file_pkg
    } else {
        panic!("Could not find data/irregular_verbs.txt at {} or {}",
               data_file_dev.display(), data_file_pkg.display());
    };

    println!("cargo:rerun-if-changed={}", data_file.display());

    // Read and parse the data file
    let file = fs::File::open(&data_file)?;
    let reader = io::BufReader::new(file);

    let mut irregular_past: Vec<(String, String)> = Vec::new();
    let mut irregular_past_participle: Vec<(String, String)> = Vec::new();
    let mut prev_base = String::new();

    for line_result in reader.lines() {
        let line = line_result?;
        let line = line.trim();
        if line.is_empty() {
            continue;
        }

        let parts: Vec<&str> = line.split('|').collect();
        if parts.len() != 3 {
            panic!("Invalid line format (expected base|past|participle): {}", line);
        }

        let base = parts[0].to_string();
        let past = parts[1].to_string();
        let participle = parts[2].to_string();

        // Sanity check: no duplicate base verbs
        if base == prev_base {
            panic!("Duplicate base verb in data file: {}", base);
        }
        prev_base = base.clone();

        irregular_past.push((base.clone(), past));
        irregular_past_participle.push((base, participle));
    }

    // Verify we got the expected number of entries
    let expected_count = 118;
    if irregular_past.len() != expected_count {
        panic!(
            "Expected {} verb entries, got {}",
            expected_count,
            irregular_past.len()
        );
    }

    // Generate Rust code for both tables
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let output_path = PathBuf::from(&out_dir).join("irregular_verbs_generated.rs");

    let mut code = String::from(
        "// Generated code: irregular verb conjugation tables\n\
         // This file is generated by build.rs from data/irregular_verbs.txt\n\n",
    );

    code.push_str("static IRREGULAR_PAST: &[(&str, &str)] = &[\n");
    for (base, past) in &irregular_past {
        code.push_str(&format!("    (\"{}\", \"{}\"),\n", base, past));
    }
    code.push_str("];\n\n");

    code.push_str("static IRREGULAR_PAST_PARTICIPLE: &[(&str, &str)] = &[\n");
    for (base, participle) in &irregular_past_participle {
        code.push_str(&format!("    (\"{}\", \"{}\"),\n", base, participle));
    }
    code.push_str("];\n");

    fs::write(&output_path, code)?;
    println!("Generated: {}", output_path.display());

    Ok(())
}
