// (c) Roel Kluin 2024 GPL v3
//! Build script for ranting_derive: generates irregular verb conjugation tables
//! from the shared data/irregular_verbs.txt file.

use std::env;
use std::fs;
use std::io::{self, BufRead};
use std::path::PathBuf;

fn main() -> io::Result<()> {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");

    generate_verbs_table(&manifest_dir)?;
    generate_plurals_table(&manifest_dir)?;
    generate_adjectives_table(&manifest_dir)?;
    copy_english_shared(&manifest_dir)?;
    copy_verb_conjugate(&manifest_dir)?;

    Ok(())
}

fn find_data_file(manifest_dir: &str, filename: &str) -> PathBuf {
    // Try to find the data file:
    // 1. First try in the symlinked/parent location (development): ../../data/{filename}
    // 2. Then try in the same package dir (cargo package verification): ./data/{filename}
    let data_file_dev = PathBuf::from(manifest_dir)
        .parent()
        .expect("parent dir")
        .join(format!("data/{}", filename));

    let data_file_pkg = PathBuf::from(manifest_dir).join(format!("data/{}", filename));

    if data_file_dev.exists() {
        data_file_dev
    } else if data_file_pkg.exists() {
        data_file_pkg
    } else {
        panic!(
            "Could not find data/{} at {} or {}",
            filename,
            data_file_dev.display(),
            data_file_pkg.display()
        );
    }
}

fn generate_verbs_table(manifest_dir: &str) -> io::Result<()> {
    let data_file = find_data_file(manifest_dir, "irregular_verbs.txt");
    println!("cargo:rerun-if-changed={}", data_file.display());

    // Read and parse the data file
    let file = fs::File::open(&data_file)?;
    let reader = io::BufReader::new(file);

    let mut irregular_past: Vec<(String, String)> = Vec::new();
    let mut irregular_past_participle: Vec<(String, String)> = Vec::new();
    let mut prev_base = String::new();

    for line_result in reader.lines() {
        let line = line_result?;
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        let parts: Vec<&str> = line.split('|').collect();
        if parts.len() != 3 {
            panic!(
                "Invalid line format (expected base|past|participle): {}",
                line
            );
        }

        let base = parts[0].to_string();
        let past = parts[1].to_string();
        let participle = parts[2].to_string();

        // Sanity check: no duplicate base verbs
        if base == prev_base {
            panic!("Duplicate base verb in data file: {}", base);
        }
        prev_base = base.clone();

        irregular_past.push((base.clone(), past));
        irregular_past_participle.push((base, participle));
    }

    // Verify we got the expected number of entries
    let expected_count = 118;
    if irregular_past.len() != expected_count {
        panic!(
            "Expected {} verb entries, got {}",
            expected_count,
            irregular_past.len()
        );
    }

    // Generate Rust code for both tables
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let output_path = PathBuf::from(&out_dir).join("irregular_verbs_generated.rs");

    let mut code = String::from(
        "// Generated code: irregular verb conjugation tables\n\
         // This file is generated by build.rs from data/irregular_verbs.txt\n\n",
    );

    code.push_str("static IRREGULAR_PAST: &[(&str, &str)] = &[\n");
    for (base, past) in &irregular_past {
        code.push_str(&format!("    (\"{}\", \"{}\"),\n", base, past));
    }
    code.push_str("];\n\n");

    code.push_str("static IRREGULAR_PAST_PARTICIPLE: &[(&str, &str)] = &[\n");
    for (base, participle) in &irregular_past_participle {
        code.push_str(&format!("    (\"{}\", \"{}\"),\n", base, participle));
    }
    code.push_str("];\n");

    fs::write(&output_path, code)?;
    println!("Generated: {}", output_path.display());

    Ok(())
}

/// Locate the canonical `english_shared.rs`, single source of truth for the
/// grammar code shared between `ranting` and `ranting_derive`. Mirrors
/// `find_data_file`'s dev/package fallback:
/// 1. Dev checkout: `../src/language/english_shared.rs`, relative to this
///    crate's manifest dir — the real file, no symlink involved.
/// 2. Packaged crate: `./data/english_shared_source.rs`, a symlink (dev) that
///    `cargo package` dereferences to real content in the published tarball,
///    since the dev path above isn't present outside the git checkout.
fn find_english_shared_file(manifest_dir: &str) -> PathBuf {
    let dev_path = PathBuf::from(manifest_dir)
        .parent()
        .expect("parent dir")
        .join("src/language/english_shared.rs");

    let pkg_path = PathBuf::from(manifest_dir).join("data/english_shared_source.rs");

    if dev_path.exists() {
        dev_path
    } else if pkg_path.exists() {
        pkg_path
    } else {
        panic!(
            "Could not find english_shared.rs at {} or {}",
            dev_path.display(),
            pkg_path.display()
        );
    }
}

/// Copy the canonical `english_shared.rs` into `OUT_DIR` so
/// `ranting_derive/src/language/english_shared.rs` can `include!()` it,
/// instead of keeping a manually-synced duplicate (see find_english_shared_file).
fn copy_english_shared(manifest_dir: &str) -> io::Result<()> {
    let source_file = find_english_shared_file(manifest_dir);
    println!("cargo:rerun-if-changed={}", source_file.display());

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let output_path = PathBuf::from(&out_dir).join("english_shared_generated.rs");

    fs::copy(&source_file, &output_path)?;

    Ok(())
}

/// Locate the canonical `verb_conjugate.rs`, single source of truth for verb
/// conjugation (to_past/to_continuous/to_future/to_past_participle), shared
/// between `ranting_derive` (compile-time say!() literal baking) and `ranting`
/// (runtime say_with!() tense resolution). Same dev/package fallback as
/// find_english_shared_file.
fn find_verb_conjugate_file(manifest_dir: &str) -> PathBuf {
    let dev_path = PathBuf::from(manifest_dir)
        .parent()
        .expect("parent dir")
        .join("src/language/verb_conjugate.rs");

    let pkg_path = PathBuf::from(manifest_dir).join("data/verb_conjugate_source.rs");

    if dev_path.exists() {
        dev_path
    } else if pkg_path.exists() {
        pkg_path
    } else {
        panic!(
            "Could not find verb_conjugate.rs at {} or {}",
            dev_path.display(),
            pkg_path.display()
        );
    }
}

/// Copy the canonical `verb_conjugate.rs` into `OUT_DIR` so
/// `ranting_derive/src/language/verb_conjugate.rs` can `include!()` it,
/// instead of keeping a manually-synced duplicate.
fn copy_verb_conjugate(manifest_dir: &str) -> io::Result<()> {
    let source_file = find_verb_conjugate_file(manifest_dir);
    println!("cargo:rerun-if-changed={}", source_file.display());

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let output_path = PathBuf::from(&out_dir).join("verb_conjugate_generated.rs");

    fs::copy(&source_file, &output_path)?;

    Ok(())
}

/// Generates the irregular comparative/superlative adjective table (used only
/// by ranting_derive for compile-time say!() degree-marker baking, see the
/// `!`/`!!` post-noun markers in src/lib.rs — `ranting` itself needs no
/// runtime copy, so this is a derive-only table with no repo-root canonical
/// `include!()` wrapper, unlike english_shared.rs/verb_conjugate.rs).
fn generate_adjectives_table(manifest_dir: &str) -> io::Result<()> {
    let data_file = find_data_file(manifest_dir, "irregular_adjectives.txt");
    println!("cargo:rerun-if-changed={}", data_file.display());

    let file = fs::File::open(&data_file)?;
    let reader = io::BufReader::new(file);

    let mut irregular_adjectives: Vec<(String, String, String)> = Vec::new();

    for line_result in reader.lines() {
        let line = line_result?;
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        let parts: Vec<&str> = line.split('|').collect();
        if parts.len() != 3 {
            panic!(
                "Invalid line format (expected base|comparative|superlative): {}",
                line
            );
        }

        let base = parts[0].to_string();
        let comparative = parts[1].to_string();
        let superlative = parts[2].to_string();

        irregular_adjectives.push((base, comparative, superlative));
    }

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let output_path = PathBuf::from(&out_dir).join("irregular_adjectives_generated.rs");

    let mut code = String::from(
        "// Generated code: irregular comparative/superlative adjective table\n\
         // This file is generated by build.rs from data/irregular_adjectives.txt\n\n",
    );

    code.push_str("static IRREGULAR_ADJECTIVES: &[(&str, &str, &str)] = &[\n");
    for (base, comparative, superlative) in &irregular_adjectives {
        code.push_str(&format!(
            "    (\"{}\", \"{}\", \"{}\"),\n",
            base, comparative, superlative
        ));
    }
    code.push_str("];\n");

    fs::write(&output_path, code)?;
    println!("Generated: {}", output_path.display());

    Ok(())
}

fn generate_plurals_table(manifest_dir: &str) -> io::Result<()> {
    let data_file = find_data_file(manifest_dir, "irregular_plurals.txt");

    // Skip if file doesn't exist yet
    if !data_file.exists() {
        return Ok(());
    }

    println!("cargo:rerun-if-changed={}", data_file.display());

    // Read and parse the data file
    let file = fs::File::open(&data_file)?;
    let reader = io::BufReader::new(file);

    let mut irregular_plurals: Vec<(String, String)> = Vec::new();

    for line_result in reader.lines() {
        let line = line_result?;
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        let parts: Vec<&str> = line.split('|').collect();
        if parts.len() != 2 {
            panic!("Invalid line format (expected singular|plural): {}", line);
        }

        let singular = parts[0].to_string();
        let plural = parts[1].to_string();

        irregular_plurals.push((singular, plural));
    }

    // Generate Rust code for the IRREGULAR_PLURALS table
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let output_path = PathBuf::from(&out_dir).join("irregular_plurals_generated.rs");

    let mut code = String::from(
        "// Generated code: irregular noun plurals table\n\
         // This file is generated by build.rs from data/irregular_plurals.txt\n\n",
    );

    code.push_str("static IRREGULAR_PLURALS: &[(&str, &str)] = &[\n");
    for (singular, plural) in &irregular_plurals {
        code.push_str(&format!("    (\"{}\", \"{}\"),\n", singular, plural));
    }
    code.push_str("];\n");

    fs::write(&output_path, code)?;
    println!("Generated: {}", output_path.display());

    Ok(())
}
