// (c) Roel Kluin 2024 MIT
//! Build script for ranting_derive: generates the comparative/superlative
//! adjective table from data/irregular_adjectives.txt.
//!
//! The irregular verb table, the placeholder grammar (`PH_START`/`PH_EXT`),
//! and the verb conjugation engine used to be copied into this crate's
//! `OUT_DIR` at build time from repo-root canonical files (see git history /
//! CLAUDE.md pre-v1.2 for the old mechanism). That copy step is gone: all of
//! it now lives in the `ranting_core` crate, which `ranting_derive` depends
//! on directly (see `ranting_core = { path = "../ranting_core" }` in
//! Cargo.toml and `use ranting_core::grammar as lang` /
//! `use ranting_core::verb_conjugate` in src/lib.rs).

use std::env;
use std::fs;
use std::io::{self, BufRead};
use std::path::PathBuf;

fn main() -> io::Result<()> {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");

    generate_adjectives_table(&manifest_dir)?;

    Ok(())
}

fn find_data_file(manifest_dir: &str, filename: &str) -> PathBuf {
    // Try to find the data file:
    // 1. First try in the symlinked/parent location (development): ../../data/{filename}
    // 2. Then try in the same package dir (cargo package verification): ./data/{filename}
    let data_file_dev = PathBuf::from(manifest_dir)
        .parent()
        .expect("parent dir")
        .join(format!("data/{}", filename));

    let data_file_pkg = PathBuf::from(manifest_dir).join(format!("data/{}", filename));

    if data_file_dev.exists() {
        data_file_dev
    } else if data_file_pkg.exists() {
        data_file_pkg
    } else {
        panic!(
            "Could not find data/{} at {} or {}",
            filename,
            data_file_dev.display(),
            data_file_pkg.display()
        );
    }
}

/// Generates the irregular comparative/superlative adjective table (used only
/// by ranting_derive for compile-time say!() degree-marker baking, see the
/// `!`/`!!` post-noun markers in src/lib.rs — `ranting` itself needs no
/// runtime copy, so this is a derive-only table with no repo-root canonical
/// `include!()` wrapper, unlike english_shared.rs/verb_conjugate.rs).
fn generate_adjectives_table(manifest_dir: &str) -> io::Result<()> {
    let data_file = find_data_file(manifest_dir, "irregular_adjectives.txt");
    println!("cargo:rerun-if-changed={}", data_file.display());

    let file = fs::File::open(&data_file)?;
    let reader = io::BufReader::new(file);

    let mut irregular_adjectives: Vec<(String, String, String)> = Vec::new();

    for line_result in reader.lines() {
        let line = line_result?;
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        let parts: Vec<&str> = line.split('|').collect();
        if parts.len() != 3 {
            panic!(
                "Invalid line format (expected base|comparative|superlative): {}",
                line
            );
        }

        let base = parts[0].to_string();
        let comparative = parts[1].to_string();
        let superlative = parts[2].to_string();

        irregular_adjectives.push((base, comparative, superlative));
    }

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let output_path = PathBuf::from(&out_dir).join("irregular_adjectives_generated.rs");

    let mut code = String::from(
        "// Generated code: irregular comparative/superlative adjective table\n\
         // This file is generated by build.rs from data/irregular_adjectives.txt\n\n",
    );

    code.push_str("static IRREGULAR_ADJECTIVES: &[(&str, &str, &str)] = &[\n");
    for (base, comparative, superlative) in &irregular_adjectives {
        code.push_str(&format!(
            "    (\"{}\", \"{}\", \"{}\"),\n",
            base, comparative, superlative
        ));
    }
    code.push_str("];\n");

    fs::write(&output_path, code)?;
    println!("Generated: {}", output_path.display());

    Ok(())
}

